es_host: elasticsearch
es_port: 9200
writeback_index: elastalert_status
buffer_time:
  minutes: 1
run_every:
  seconds: 60
rules_folder: /opt/elastalert/rules
smtp_host: localhost
smtp_port: 2525
smtp_ssl: false
from_addr: dcfran@gmail.com
smtp_auth_file: /opt/elastalert/smtp_auth.yaml